/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AnnotateTab: typeof import('./src/components/ui/AnnotateTab.vue')['default']
    AnnotationItemsViewer: typeof import('./src/components/modals/metadata/AnnotationItemsViewer.vue')['default']
    AnnotationSelect: typeof import('./src/components/input/select/AnnotationSelect.vue')['default']
    AnnotationSummary: typeof import('./src/components/tables/AnnotationSummary.vue')['default']
    AppBanner: typeof import('./src/components/ui/AppBanner.vue')['default']
    AttributionsViewer: typeof import('./src/components/modals/metadata/AttributionsViewer.vue')['default']
    BenchmarkSetsHelp: typeof import('./src/components/help/BenchmarkSetsHelp.vue')['default']
    ComparisonModal: typeof import('./src/components/modals/evaluation/ComparisonModal.vue')['default']
    CorporaTable: typeof import('./src/components/tables/annotate/CorporaTable.vue')['default']
    CorpusHelp: typeof import('./src/components/help/CorpusHelp.vue')['default']
    CorpusModal: typeof import('./src/components/modals/corpus/CorpusModal.vue')['default']
    CorpusModalHelp: typeof import('./src/components/help/CorpusModalHelp.vue')['default']
    CorpusModalUserList: typeof import('./src/components/modals/corpus/CorpusModalUserList.vue')['default']
    DeleteButton: typeof import('./src/components/input/button/DeleteButton.vue')['default']
    DeleteModal: typeof import('./src/components/modals/DeleteModal.vue')['default']
    DifferentTagsetsHelp: typeof import('./src/components/help/DifferentTagsetsHelp.vue')['default']
    DocumentEntitiesTable: typeof import('./src/components/tables/evaluation/DocumentEntitiesTable.vue')['default']
    DocumentSelect: typeof import('./src/components/input/select/DocumentSelect.vue')['default']
    DocumentsHelp: typeof import('./src/components/help/DocumentsHelp.vue')['default']
    DocumentsTable: typeof import('./src/components/tables/annotate/DocumentsTable.vue')['default']
    DownloadButton: typeof import('./src/components/input/button/DownloadButton.vue')['default']
    EvaluateHelp: typeof import('./src/components/help/EvaluateHelp.vue')['default']
    ExportHelp: typeof import('./src/components/help/ExportHelp.vue')['default']
    ExternalLink: typeof import('./src/components/links/ExternalLink.vue')['default']
    FormatSelect: typeof import('./src/components/input/select/FormatSelect.vue')['default']
    GButton: typeof import('./src/components/input/button/GButton.vue')['default']
    GCard: typeof import('./src/components/ui/GCard.vue')['default']
    GCheckBox: typeof import('./src/components/input/GCheckBox.vue')['default']
    GFooter: typeof import('./src/components/ui/GFooter.vue')['default']
    GForm: typeof import('./src/components/input/GForm.vue')['default']
    GInfo: typeof import('./src/components/ui/GInfo.vue')['default']
    GInput: typeof import('./src/components/input/GInput.vue')['default']
    GModal: typeof import('./src/components/modals/GModal.vue')['default']
    GNumber: typeof import('./src/components/input/GNumber.vue')['default']
    GSelect: typeof import('./src/components/input/select/GSelect.vue')['default']
    GSpinner: typeof import('./src/components/ui/GSpinner.vue')['default']
    GTable: typeof import('./src/components/tables/GTable.vue')['default']
    GTablePaginator: typeof import('./src/components/tables/GTablePaginator.vue')['default']
    GTabs: typeof import('./src/components/ui/GTabs.vue')['default']
    GValidator: typeof import('./src/components/input/GValidator.vue')['default']
    HelpLink: typeof import('./src/components/links/HelpLink.vue')['default']
    InlineTextButton: typeof import('./src/components/input/button/InlineTextButton.vue')['default']
    InspectButton: typeof import('./src/components/input/button/InspectButton.vue')['default']
    JobModal: typeof import('./src/components/modals/jobs/JobModal.vue')['default']
    JobModalHelp: typeof import('./src/components/help/JobModalHelp.vue')['default']
    JobProgress: typeof import('./src/components/modals/jobs/JobProgress.vue')['default']
    JobProgressSegment: typeof import('./src/components/modals/jobs/JobProgressSegment.vue')['default']
    JobSelect: typeof import('./src/components/input/select/JobSelect.vue')['default']
    JobsHelp: typeof import('./src/components/help/JobsHelp.vue')['default']
    JobsTable: typeof import('./src/components/tables/annotate/JobsTable.vue')['default']
    KeyValues: typeof import('./src/components/ui/KeyValues.vue')['default']
    LayerViewer: typeof import('./src/components/tables/LayerViewer.vue')['default']
    MailAddress: typeof import('./src/components/links/MailAddress.vue')['default']
    MetricsFilter: typeof import('./src/components/tables/evaluation/MetricsFilter.vue')['default']
    MetricsTable: typeof import('./src/components/tables/evaluation/MetricsTable.vue')['default']
    RightFloatCell: typeof import('./src/components/tables/RightFloatCell.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SingleTermComparisonTable: typeof import('./src/components/tables/evaluation/SingleTermComparisonTable.vue')['default']
    TaggerQueue: typeof import('./src/components/modals/jobs/TaggerQueue.vue')['default']
    TagsetSelect: typeof import('./src/components/input/select/TagsetSelect.vue')['default']
    TypeTokenModal: typeof import('./src/components/modals/evaluation/TypeTokenModal.vue')['default']
    UploadDocuments: typeof import('./src/components/input/UploadDocuments.vue')['default']
  }
}
