/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AnnotateTab: typeof import('./src/components/AnnotateTab.vue')['default']
    AppBanner: typeof import('./src/components/AppBanner.vue')['default']
    BenchmarkSetsHelp: typeof import('./src/components/help/BenchmarkSetsHelp.vue')['default']
    ComparisonModal: typeof import('./src/components/modals/ComparisonModal.vue')['default']
    CorpusForm: typeof import('./src/components/modals/corpus/CorpusForm.vue')['default']
    CorpusFormHelp: typeof import('./src/components/help/CorpusFormHelp.vue')['default']
    CorpusHelp: typeof import('./src/components/help/CorpusHelp.vue')['default']
    CorpusTable: typeof import('./src/components/tables/CorpusTable.vue')['default']
    DeleteModal: typeof import('./src/components/modals/DeleteModal.vue')['default']
    DifferentTagsetsHelp: typeof import('./src/components/help/DifferentTagsetsHelp.vue')['default']
    DocumentsHelp: typeof import('./src/components/help/DocumentsHelp.vue')['default']
    DocumentsTable: typeof import('./src/components/tables/DocumentsTable.vue')['default']
    DownloadButton: typeof import('./src/components/input/DownloadButton.vue')['default']
    EvaluateHelp: typeof import('./src/components/help/EvaluateHelp.vue')['default']
    EvaluationInfoBox: typeof import('./src/components/EvaluationInfoBox.vue')['default']
    ExportHelp: typeof import('./src/components/help/ExportHelp.vue')['default']
    ExternalLink: typeof import('./src/components/links/ExternalLink.vue')['default']
    FileFormatInput: typeof import('./src/components/input/FileFormatInput.vue')['default']
    GButton: typeof import('./src/components/input/GButton.vue')['default']
    GCard: typeof import('./src/components/GCard.vue')['default']
    GInfo: typeof import('./src/components/GInfo.vue')['default']
    GInput: typeof import('./src/components/input/GInput.vue')['default']
    GModal: typeof import('./src/components/modals/GModal.vue')['default']
    GNav: typeof import('./src/components/links/GNav.vue')['default']
    GSpinner: typeof import('./src/components/GSpinner.vue')['default']
    GTable: typeof import('./src/components/tables/GTable.vue')['default']
    GTabs: typeof import('./src/components/GTabs.vue')['default']
    HelpLink: typeof import('./src/components/links/HelpLink.vue')['default']
    InspectButton: typeof import('./src/components/input/InspectButton.vue')['default']
    JobModal: typeof import('./src/components/modals/jobs/JobModal.vue')['default']
    JobProgress: typeof import('./src/components/modals/jobs/JobProgress.vue')['default']
    JobProgressSegment: typeof import('./src/components/modals/jobs/JobProgressSegment.vue')['default']
    JobSelect: typeof import('./src/components/input/JobSelect.vue')['default']
    JobsHelp: typeof import('./src/components/help/JobsHelp.vue')['default']
    KeyValues: typeof import('./src/components/KeyValues.vue')['default']
    LayerViewer: typeof import('./src/components/tables/LayerViewer.vue')['default']
    MailAddress: typeof import('./src/components/links/MailAddress.vue')['default']
    MetricsFilter: typeof import('./src/components/tables/MetricsFilter.vue')['default']
    MetricsTable: typeof import('./src/components/tables/MetricsTable.vue')['default']
    RightFloatCell: typeof import('./src/components/tables/RightFloatCell.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SingleTermComparisonTable: typeof import('./src/components/tables/SingleTermComparisonTable.vue')['default']
    UploadDocuments: typeof import('./src/components/input/UploadDocuments.vue')['default']
    UserList: typeof import('./src/components/modals/corpus/UserList.vue')['default']
    VariantsModal: typeof import('./src/components/modals/VariantsModal.vue')['default']
  }
}
