# Docker compose file for galahad client, server and proxy
services:
    client:
        image: instituutnederlandsetaal/galahad-client:${APP_VERSION}
        build:
            context: client
        restart: unless-stopped
        networks:
            - proxy_network
        deploy:
            resources:
                limits:
                    cpus: '0.50'
                    memory: 512M
                reservations:
                    cpus: '0.25'
                    memory: 128M
    server:
        image: instituutnederlandsetaal/galahad-server:${APP_VERSION}
        build:
            context: server
        restart: unless-stopped
        volumes:
            - user-corpora-volume:/data/corpora/custom
            - preset-corpora-volume:/data/corpora/presets
            - admins-volume:/data/admins
        networks:
            - proxy_network
            - taggers
        deploy:
            resources:
                limits:
                    cpus: '2.00'
                    memory: 8G # should be higher that the java heap size
                reservations:
                    cpus: '1.00'
                    memory: 2G
        environment: # Otherwise container doesn't restart on OutOfMemory
            - "JAVA_OPTS=-XX:+ExitOnOutOfMemoryError"
    proxy:
        image: nginx:1.27.3-alpine3.20
        volumes:
            - ./proxy/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - client
            - server
        ports:
            - "80:80"
        restart: unless-stopped
        networks:
            - proxy_network


networks:
    front:
        driver: bridge
    proxy_network:
        driver: bridge
    taggers:
        external: true
        name: $taggers_network
volumes:
    user-corpora-volume:
    preset-corpora-volume:
    formats-volume:
    taggers-volume:
    tagsets-volume:
    admins-volume:
