logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=INFO
logging.pattern.console=%clr(%d{${LOG_DATEFORMAT_PATTERN:yyyy-MM-dd HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}
# https://stackoverflow.com/questions/72235752/cannot-invoke-org-springframework-web-servlet-mvc-condition-patternsrequestcond
spring.mvc.pathmatch.matching-strategy=ant_path_matcher
# disable petstore, auto try-it-out
springdoc.swagger-ui.disable-swagger-default-url=true
springdoc.swagger-ui.try-it-out-enabled=true
# forward headers strategy
server.use-forward-headers=true
server.forward-headers-strategy=framework
# setup swagger to work behind clarin
springdoc.swagger-ui.config-url=/galahad/api/v3/api-docs/swagger-config
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.url=/galahad/api/v3/api-docs
springdoc.default-produces-media-type=application/json
