# logging
logging.level.org.ivdnt.galahad=DEBUG
galahad.logging.cache-period=PT1M

# swagger without clarin
springdoc.swagger-ui.config-url=/v3/api-docs/swagger-config
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.url=/v3/api-docs
