# disable petstore, auto try-it-out
springdoc.swagger-ui.disable-swagger-default-url=true
springdoc.swagger-ui.try-it-out-enabled=true

# swagger without clarin
springdoc.swagger-ui.config-url=/v3/api-docs/swagger-config
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.url=/v3/api-docs
